name: Secretos Demo

on: [push, workflow_dispatch]

jobs:
  demo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Usar Secreto
        env:
          MI_SECRETO: ${{ secrets.GUAPLI_ECRET }}
        run: |
          echo "Los secretos se ocultan autom√°ticamente en los logs:"
          echo "Valor del secreto: $MI_SECRETO"
          echo "Acceso directo: ${{ secrets.GUAPLI_ECRET }}"
